import type { Metadata } from "next";
import {Fjalla_One} from "next/font/google"
import Header from "./components/ui/header/Header";
import "./globals.css";
import Footer from "./components/ui/footer/Footer";

const fjalla_One = Fjalla_One({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: "Evolura",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fjalla_One.className} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
